version: "3.8"

services:
  front:
    build:
      context: .
      args:
        WORKDIR: $WORKDIR
        CONTAINER_PORT: $CONTAINER_PORT
        API_URL: "http://localhost:$API_PORT"
    command: yarn run dev
    volumes:
      - .:/$WORKDIR
    ports:
      - "$FRONT_PORT:$CONTAINER_PORT"
